dataset_path: Bleking/floorplan_dataset_wilder
dataset_kwargs:
  token: True
task: "floorplan_test_wilder"
test_split: test 
lmms_eval_specific_kwargs:
  default:
    pre_prompt: ""
    post_prompt: ""
  xcomposer2_4khd:
    pre_prompt: "[UNUSED_TOKEN_146]user\nQuestion: "
    post_prompt: "[UNUSED_TOKEN_145]\n[UNUSED_TOKEN_146]assistant\n"
include: _default_template_wilder_yaml
